// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 登录请求体
type LoginRequest struct {
	//@inject_tag: json:"username"
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username"`
	//@inject_tag: json:"password"
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// 登录响应体
type LoginResponse struct {
	//@inject_tag: json:"token"
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token"`
	//@inject_tag: json:"expires"
	Expires              string   `protobuf:"bytes,2,opt,name=expires,proto3" json:"expires"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetExpires() string {
	if m != nil {
		return m.Expires
	}
	return ""
}

// 注册请求体
type RegisterRequest struct {
	//@inject_tag: validate:"required" json:"nickname"
	Nickname string `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname" validate:"required"`
	//@inject_tag: validate:"required,gte=11" message:"required:手机号不能为空,gt:手机号不正确" json:"phone"
	Phone string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone" validate:"required,gte=11" message:"required:手机号不能为空,gt:手机号不正确"`
	//@inject_tag: validate:"required" json:"password"
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password" validate:"required"`
	//@inject_tag: validate:"required" json:"code"
	Code                 string   `protobuf:"bytes,4,opt,name=code,proto3" json:"code" validate:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *RegisterRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

// 注册响应
type RegisterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

// 账号信息请求体
type InfoRequest struct {
	//@inject_tag: validate:"required" json:"authorization"
	Authorization        string   `protobuf:"bytes,1,opt,name=Authorization,proto3" json:"authorization" validate:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoRequest) Reset()         { *m = InfoRequest{} }
func (m *InfoRequest) String() string { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()    {}
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{4}
}

func (m *InfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoRequest.Unmarshal(m, b)
}
func (m *InfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoRequest.Marshal(b, m, deterministic)
}
func (m *InfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoRequest.Merge(m, src)
}
func (m *InfoRequest) XXX_Size() int {
	return xxx_messageInfo_InfoRequest.Size(m)
}
func (m *InfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InfoRequest proto.InternalMessageInfo

func (m *InfoRequest) GetAuthorization() string {
	if m != nil {
		return m.Authorization
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "LoginResponse")
	proto.RegisterType((*RegisterRequest)(nil), "RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "RegisterResponse")
	proto.RegisterType((*InfoRequest)(nil), "InfoRequest")
}

func init() {
	proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0)
}

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xc1, 0x4b, 0x33, 0x31,
	0x10, 0xc5, 0xe9, 0xf7, 0xb5, 0x6e, 0x3b, 0xba, 0x5a, 0x83, 0x87, 0x65, 0x4f, 0x12, 0x44, 0x3c,
	0x45, 0xb0, 0x47, 0x0f, 0x52, 0x0f, 0x82, 0xe0, 0x69, 0x8f, 0xde, 0xb6, 0xdb, 0xb1, 0x0d, 0xc5,
	0x4c, 0xcc, 0x64, 0x51, 0xfc, 0xeb, 0xa5, 0xc9, 0x46, 0x77, 0x7b, 0x4a, 0xde, 0x0c, 0xbc, 0xf9,
	0xcd, 0x1b, 0xc8, 0xeb, 0xa6, 0xa1, 0xd6, 0x78, 0x65, 0x1d, 0x79, 0x92, 0x4f, 0x70, 0xf2, 0x42,
	0x1b, 0x6d, 0x2a, 0xfc, 0x68, 0x91, 0xbd, 0x28, 0x61, 0xda, 0x32, 0x3a, 0x53, 0xbf, 0x63, 0x31,
	0xba, 0x1c, 0xdd, 0xcc, 0xaa, 0x5f, 0xbd, 0xef, 0xd9, 0x9a, 0xf9, 0x93, 0xdc, 0xba, 0xf8, 0x17,
	0x7b, 0x49, 0xcb, 0x07, 0xc8, 0x3b, 0x1f, 0xb6, 0x64, 0x18, 0xc5, 0x05, 0x4c, 0x3c, 0xed, 0xd0,
	0x74, 0x2e, 0x51, 0x88, 0x02, 0x32, 0xfc, 0xb2, 0xda, 0x21, 0x77, 0x0e, 0x49, 0x4a, 0x86, 0xb3,
	0x0a, 0x37, 0x9a, 0x3d, 0xba, 0x1e, 0x8b, 0xd1, 0xcd, 0xae, 0xcf, 0x92, 0xf4, 0xde, 0xde, 0x6e,
	0xc9, 0x60, 0x67, 0x13, 0xc5, 0x80, 0xf0, 0xff, 0x90, 0x50, 0x08, 0x18, 0x37, 0xb4, 0xc6, 0x62,
	0x1c, 0xea, 0xe1, 0x2f, 0x05, 0xcc, 0xff, 0x86, 0x46, 0x70, 0xb9, 0x80, 0xe3, 0x67, 0xf3, 0x46,
	0x09, 0xe2, 0x0a, 0xf2, 0x65, 0xeb, 0xb7, 0xe4, 0xf4, 0x77, 0xed, 0x35, 0xa5, 0x7d, 0x86, 0xc5,
	0xbb, 0x15, 0x64, 0xcb, 0x98, 0xab, 0xb8, 0x86, 0x49, 0x48, 0x42, 0xe4, 0xaa, 0x9f, 0x6c, 0x79,
	0xaa, 0x86, 0x01, 0xdd, 0xc2, 0x34, 0xcd, 0x16, 0x73, 0x75, 0xb0, 0x7b, 0x79, 0xae, 0x0e, 0xc1,
	0x1e, 0x67, 0xaf, 0x99, 0xba, 0x0f, 0x57, 0x5b, 0x1d, 0x85, 0x67, 0xf1, 0x13, 0x00, 0x00, 0xff,
	0xff, 0x0f, 0xc6, 0x3d, 0x76, 0xcd, 0x01, 0x00, 0x00,
}
